spring.profiles.active: production
spring.main.show-banner: true

app.name: gn
app.description: good news for everyone

# LOGGING
logging.path: ./var/log
logging.file: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO

# ELASTICSEARCH
spring.data.elasticsearch:
  cluster-name: elasticsearch-cluster
  cluster-nodes: # The address(es) of the server node (comma-separated; if not specified starts a client node)
  repositories.enabled: true
  properties:
    index.refresh_interval: 60s
    path.data: data/
    threadpool:
      index:
        type: fixed
        size: 4
        queue_size: 1000
      search:
        type: fixed
        size: 8
        queue_size: 1000
      refresh:
        type: fixed
        size: 2
        queue_size: 1000